build: off

install:
  - ps: Install-Product node 8
  - git submodule update --init --recursive
  - yarn install
  - yarn install-plugins
  - yarn ci:compile

test_script:
  - yarn screentest
  - 7z a screentest.zip test-dist\screentest\*
  - ps: $env:changed_screens = (Get-Content -Raw -Path test-dist\screentest\state.json | ConvertFrom-Json).changedScreens
  - ps: if ($env:changed_screens -gt 0) {Add-AppveyorMessage "$env:changed_screens screens have been changed"}

artifacts:
  - path: 'screentest.zip'
    name: Screentests

notifications:
  - provider: GitHubPullRequest
    template: "{{#failed}}:x: Build failed {{/failed}}{{#passed}} {{#messages}}:warning: {{.}} {{/messages}} {{^messages}}:white_check_mark: Screens are not changed {{/messages}} Tests passed{{/passed}}"