build: off

install:
  - ps: Install-Product node 8
  - git submodule update --init --recursive
  - yarn install
  - yarn install-plugins
  - yarn ci:compile

test_script:
  - yarn screentest
  - 7z a screentest.zip test-dist\screentest\*

artifacts:
  - path: 'screentest.zip'
    name: Screentests